#!/usr/bin/env python3
"""Prepare training splits for Phase 1 (tool selection) fine-tuning.

Reads both synthetic conversations and real annotated images, transforms
them into 3-message sequences (system + user image + assistant tool call),
filters out eval-set images, and writes train/val/tiny JSONL splits.

Usage:
    python fine_tuning/qwen/data_prep.py
    python fine_tuning/qwen/data_prep.py --output-dir datasets/splits
"""

import argparse
import json
import logging
import random
from pathlib import Path

from evaluation.prompt import NO_TOOL_RESPONSE, SYSTEM_PROMPT

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

SCREEN_TYPES = ["caught_fish", "no_tools", "pierre_shop", "tv_dialog"]

# no_tools has no synthetic data — real screenshots only, since the visual
# variation is too broad for compositing. The other classes use synthetic
# images generated by overlaying text on clean backgrounds.
SCREEN_TYPES_WITH_SYNTHETIC = ["caught_fish", "pierre_shop", "tv_dialog"]

TOOL_FOR_SCREEN = {
    "caught_fish": "crop_caught_fish_notification",
    "pierre_shop": "crop_pierres_detail_panel",
    "tv_dialog": "crop_tv_dialog",
}

TINY_PER_CLASS = 10
SEED = 42
VAL_FRACTION = 0.15
NO_TOOLS_TRAIN_RATIO = 2.0  # no_tools train examples per tool-class train average


def load_eval_image_paths(eval_set_path: Path) -> set[str]:
    with open(eval_set_path) as f:
        eval_set = json.load(f)
    return {item["image_path"] for item in eval_set}


def format_tool_call(tool_name: str) -> str:
    call = json.dumps({"name": tool_name, "arguments": {}})
    return f"<tool_call>\n{call}\n</tool_call>"


def transform_conversation(record: dict) -> dict | None:
    """Transform a synthetic conversation into a Phase 1 training example.

    Returns a 3-message conversation: system, user (image+text), assistant (tool call or refusal).
    """
    messages = record["messages"]
    screen_type = record["metadata"]["screen_type"]

    user_msg = messages[0]
    if user_msg["role"] != "user":
        logger.warning("Unexpected first message role: %s", user_msg["role"])
        return None

    if screen_type in TOOL_FOR_SCREEN:
        assistant_content = format_tool_call(TOOL_FOR_SCREEN[screen_type])
    else:
        assistant_content = NO_TOOL_RESPONSE

    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            user_msg,
            {"role": "assistant", "content": assistant_content},
        ],
        "metadata": record["metadata"],
    }


def annotation_to_conversation(annotation: dict) -> dict:
    """Convert a real image annotation into a synthetic-style conversation record."""
    screen_type = annotation["screen_type"]
    image_path = annotation["image_path"]

    user_msg = {
        "role": "user",
        "content": [
            {"type": "image", "image": f"file://{image_path}"},
            {"type": "text", "text": "What's on this screen?"},
        ],
    }

    if screen_type in TOOL_FOR_SCREEN:
        assistant_content = format_tool_call(TOOL_FOR_SCREEN[screen_type])
    else:
        assistant_content = NO_TOOL_RESPONSE

    return {
        "messages": [user_msg],
        "metadata": {"screen_type": screen_type, "synthetic": False},
    }


def load_and_transform(
    synthetic_dir: Path, datasets_dir: Path, eval_images: set[str]
) -> list[dict]:
    examples = []
    skipped_eval = 0

    for screen_type in SCREEN_TYPES:
        count_synthetic = 0
        count_real = 0

        # Load synthetic conversations (not available for no_tools)
        conv_file = synthetic_dir / screen_type / "conversations.jsonl"
        if conv_file.exists():
            with open(conv_file) as f:
                for line in f:
                    record = json.loads(line)
                    image_path = record["messages"][0]["content"][0]["image"]
                    clean_path = image_path.removeprefix("file://")

                    if clean_path in eval_images:
                        skipped_eval += 1
                        continue

                    transformed = transform_conversation(record)
                    if transformed:
                        examples.append(transformed)
                        count_synthetic += 1

        # Load real annotated images
        ann_file = datasets_dir / screen_type / "annotations.jsonl"
        if ann_file.exists():
            with open(ann_file) as f:
                for line in f:
                    if not line.strip():
                        continue
                    annotation = json.loads(line)
                    image_path = annotation["image_path"]

                    if image_path in eval_images:
                        skipped_eval += 1
                        continue

                    record = annotation_to_conversation(annotation)
                    transformed = transform_conversation(record)
                    if transformed:
                        examples.append(transformed)
                        count_real += 1

        logger.info(
            "%-15s: %d synthetic + %d real = %d examples",
            screen_type, count_synthetic, count_real,
            count_synthetic + count_real,
        )

    logger.info("Skipped %d eval-set images", skipped_eval)
    return examples


def write_jsonl(records: list[dict], path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        for record in records:
            f.write(json.dumps(record) + "\n")
    logger.info("Wrote %d records to %s", len(records), path)


def make_tiny_split(examples: list[dict], per_class: int) -> list[dict]:
    by_type: dict[str, list[dict]] = {}
    for ex in examples:
        st = ex["metadata"]["screen_type"]
        by_type.setdefault(st, []).append(ex)

    tiny = []
    for st in SCREEN_TYPES:
        pool = by_type.get(st, [])
        n = min(per_class, len(pool))
        tiny.extend(pool[:n])

    random.shuffle(tiny)
    return tiny


def main():
    parser = argparse.ArgumentParser(description="Prepare Phase 1 training splits")
    parser.add_argument(
        "--datasets-dir",
        type=Path,
        default=Path("datasets"),
    )
    parser.add_argument(
        "--synthetic-dir",
        type=Path,
        default=Path("datasets/synthetic"),
    )
    parser.add_argument(
        "--eval-set",
        type=Path,
        default=Path("datasets/eval_set.json"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("datasets/splits"),
    )
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--val-fraction", type=float, default=VAL_FRACTION)
    parser.add_argument("--tiny-per-class", type=int, default=TINY_PER_CLASS)
    args = parser.parse_args()

    random.seed(args.seed)

    eval_images = load_eval_image_paths(args.eval_set)
    logger.info("Eval set: %d images to exclude", len(eval_images))

    examples = load_and_transform(args.synthetic_dir, args.datasets_dir, eval_images)
    random.shuffle(examples)

    # Split tool-calling classes at the standard ratio, then cap no_tools
    # training at NO_TOOLS_TRAIN_RATIO:1 vs the average tool class, with
    # overflow going to validation.
    tool_examples = [ex for ex in examples if ex["metadata"]["screen_type"] != "no_tools"]
    no_tools_examples = [ex for ex in examples if ex["metadata"]["screen_type"] == "no_tools"]

    tool_split_idx = int(len(tool_examples) * (1 - args.val_fraction))
    tool_train = tool_examples[:tool_split_idx]
    tool_val = tool_examples[tool_split_idx:]

    # Calculate no_tools train target: 2:1 vs average tool class in train
    tool_class_counts = {}
    for ex in tool_train:
        st = ex["metadata"]["screen_type"]
        tool_class_counts[st] = tool_class_counts.get(st, 0) + 1
    avg_tool_train = sum(tool_class_counts.values()) / max(len(tool_class_counts), 1)
    no_tools_train_target = int(NO_TOOLS_TRAIN_RATIO * avg_tool_train)

    no_tools_train = no_tools_examples[:no_tools_train_target]
    no_tools_val = no_tools_examples[no_tools_train_target:]

    train = tool_train + no_tools_train
    val = tool_val + no_tools_val
    random.shuffle(train)
    random.shuffle(val)

    logger.info("Tool class train avg: %.0f, no_tools train target (%.0f:1): %d",
                avg_tool_train, NO_TOOLS_TRAIN_RATIO, no_tools_train_target)
    logger.info("Split: %d train, %d val", len(train), len(val))

    tiny = make_tiny_split(train, args.tiny_per_class)

    write_jsonl(train, args.output_dir / "train.jsonl")
    write_jsonl(val, args.output_dir / "val.jsonl")
    write_jsonl(tiny, args.output_dir / "train_tiny.jsonl")

    # Summary by class
    for split_name, split_data in [("train", train), ("val", val), ("tiny", tiny)]:
        counts = {}
        for ex in split_data:
            st = ex["metadata"]["screen_type"]
            counts[st] = counts.get(st, 0) + 1
        logger.info("%s breakdown: %s", split_name, counts)


if __name__ == "__main__":
    main()
